version: '3'
services: 
    fastapi:
        build: ./fastapi/
        depends_on: 
            - tf_serving
        ports: 
            - 8000:8000
        networks: 
            - xlm_network
        
    tf_serving:
        image: tensorflow/serving:latest
        container_name: model_server
        ports: 
            - 8501:8501
        networks: 
            - xlm_network
        volumes: 
            - ./tf_serving/models/:/models
        command: --rest_api_port=8501 --model_base_path='/models/' --model_name='xlm_model'

networks:
    xlm_network:
        driver: bridge